@echo off
echo Clearing Flutter cache...
flutter clean
echo Clearing Gradle cache...
rmdir /s /q "C:\Users\ragha\.gradle\caches"
echo Clearing Pub cache...
flutter pub cache clean
echo Clearing Dart tool cache...
rmdir /s /q ".dart_tool"
echo Getting dependencies...
flutter pub get
echo Cache cleared successfully!
pause