name: qasetha
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  firebase_performance: ^0.10.0+8
  firebase_app_check: ^0.3.1+3
  flutter_secure_storage: ^9.2.2
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  logger: ^2.4.0
  # local_auth removed
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  lottie: ^3.1.2
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.8
  firebase_storage: ^12.4.9
  image_picker: ^1.0.4
  sms_autofill: ^2.3.0
  intl: 0.20.2
  connectivity_plus: ^6.0.5
  dio: ^5.7.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/