// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ..
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3v5_lSdNp2vWmLlEGPOuQY-kqkmM3VA',
    appId: '1:249998545764:web:8d695cfddc94734c3ca071',
    messagingSenderId: '249998545764',
    projectId: 'qasetha-app',
    authDomain: 'qasetha-app.firebaseapp.com',
    storageBucket: 'qasetha-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa3v5_lSdNp2vWmLlEGPOuQY-kqkmM3VA',
    appId: '1:249998545764:android:8d695cfddc94734c3ca071',
    messagingSenderId: '249998545764',
    projectId: 'qasetha-app',
    storageBucket: 'qasetha-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxC5-IcnyVsBgbGr9w5nQe25ObO4HDy8c',
    appId: '1:249998545764:ios:b595e6efd4782dc13ca071',
    messagingSenderId: '249998545764',
    projectId: 'qasetha-app',
    storageBucket: 'qasetha-app.firebasestorage.app',
    iosBundleId: 'com.qaseth.app.qasetha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxC5-IcnyVsBgbGr9w5nQe25ObO4HDy8c',
    appId: '1:249998545764:ios:b595e6efd4782dc13ca071',
    messagingSenderId: '249998545764',
    projectId: 'qasetha-app',
    storageBucket: 'qasetha-app.firebasestorage.app',
    iosBundleId: 'com.qaseth.app.qasetha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa3v5_lSdNp2vWmLlEGPOuQY-kqkmM3VA',
    appId: '1:249998545764:web:8d695cfddc94734c3ca071',
    messagingSenderId: '249998545764',
    projectId: 'qasetha-app',
    authDomain: 'qasetha-app.firebaseapp.com',
    storageBucket: 'qasetha-app.firebasestorage.app',
  );
}
